# Generated by Django 4.2.16 on 2024-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chronic_disease', models.BooleanField(default=True)),
                ('disease_type', models.CharField(max_length=100)),
                ('is_on_medication', models.BooleanField(default=True)),
                ('medication_name', models.CharField(max_length=100)),
                ('is_allergic', models.BooleanField(default=True)),
                ('allergy', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
