# Generated by Django 4.2.16 on 2024-12-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_allergic',
            field=models.BinaryField(default=False, max_length='max'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_chronic_disease',
            field=models.BinaryField(default=False, max_length='max'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='is_on_medication',
            field=models.BinaryField(default=False, max_length='max'),
        ),
    ]
