# Generated by Django 4.2.16 on 2024-12-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_delete_userprofile_alter_medicalhistory_is_allergic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='disease_type',
        ),
    ]
