# Generated by Django 4.2.16 on 2024-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_medicalhistory_disease_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='disease_type',
            field=models.TextField(default='none'),
        ),
    ]
